sudo: false
language: ruby
rvm:
  - 2.2.0
  - 2.3.0
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
notifications:
  email: false
script:
  - bundle exec rake db:migrate
  - bundle exec rspec
services: mongodb
env:
  - ORM=mongoid
  - ORM=active_record
